apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretclaims.vaultproject.io
spec:
  group: vaultproject.io
  names:
    kind: SecretClaim
    listKind: SecretClaimList
    plural: secretclaims
    singular: secretclaim
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              path:
                type: string
                pattern: '^.*?\/.*?(\/.*?)?$'
              kv:
                type: string
                enum:
                - v1
                - v2
                default: v2
    additionalPrinterColumns:
    - name: Path
      type: string
      description: Path in vault to get secret data
      jsonPath: .spec.path
    - name: Kv
      type: string
      description: Kv storage version 1 or 2
      jsonPath: .spec.kv
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
