apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretclaims.vaultproject.io
spec:
  group: vaultproject.io
  names:
    kind: SecretClaim
    listKind: SecretClaimList
    plural: secretclaims
    singular: secretclaim
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              path:
                type: string
                pattern: '^.*?\/.*?(\/.*?)?$'
              kv:
                type: string
                enum:
                - v1
                - v2
                default: v2
          status:
            type: object
            properties:
              state:
                type: string
              lastSyncTime:
                format: date-time
                type: string
              lastChangedTime:
                format: date-time
                type: string
        required:
          - spec
    additionalPrinterColumns:
    - name: Path
      type: string
      description: Path in vault to get secret data
      jsonPath: .spec.path
    - name: Kv
      type: string
      description: Kv storage version 1 or 2
      jsonPath: .spec.kv
    - name: Status
      type: string
      description: Sync status
      jsonPath: .status.state
    - name: Modified
      type: date
      jsonPath: .status.lastChangedTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
